config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users do
    resources :stashes, except: [:edit, :update, :show]
    resources :friendships, only: [:new, :create, :destroy]
  end

  resources :sessions, only: [:create, :new, :destroy]

  resources :games do
    resources :comments, only: [:index, :create, :destroy]
    member do
      post 'upvote' => 'votes#upvote'
      post 'downvote' => 'votes#downvote'
    end
  end

  resources :categories, only: [:index, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :games_categories
  has_many :games, through: :games_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commenter, class_name: 'User'
  belongs_to :game
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :friend, class_name: "User"
  belongs_to :user
  has_many :groups

  validates :friend, uniqueness: {scope: :user, message: "cannot friend same person twice"}
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :games_categories
  has_many :categories, through: :games_categories
  has_many :stashes
  has_many :users, through: :stashes
  has_many :comments
  has_many :votes
  has_many :user_votes, through: :votes, source: :user

  def vote_score
    self.votes.map(&:value).reduce(:+) || 0
  end
end

app/models/games_category.rb
class GamesCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :game
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  has_many :groupings
  has_many :friendships, through: :groupings
  has_many :friends, through: :friendships
end

app/models/grouping.rb
class Grouping < ActiveRecord::Base
  belongs_to :friendship
  belongs_to :group
end

app/models/stash.rb
class Stash < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  validates :game, uniqueness: { scope: :user, message: "cannot be added twice to your games" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stashes
  has_many :games, through: :stashes
  has_many :friendships
  has_many :groups, foreign_key: :creator_id
  has_many :friends, through: :friendships, source: :friend
  has_many :comments, foreign_key: :commenter_id
  has_many :votes
  has_many :voted_on_games, through: :vote, source: :game

  has_secure_password
  validates :email, presence: true, uniqueness: true

  def does_not_suck?
    return true
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :game

  validates :user_id, uniqueness: { scope: :game_id, message: "has already voted on this game" }
  validates :value, inclusion: { in: [1, -1] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include CurrentUserHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Game.find(params[:game_id]).comments
  end

  def create
    game = Game.find(params[:game_id])
    @comment = current_user.comments.build(comment_params)
    @comment.game = game
    if @comment.save
      redirect_to game_path(game)
    else
      flash[:alert] = "Comment did not save."
      redirect_to game_path(game)
    end
  end

  def destroy
    game = Game.find(params[:game_id])
    comment = Comment.find(params[:id])
    if comment.commenter == current_user
      comment.destroy
    end
    redirect_to game_path(game)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash[:login] = 'Try again... ԅ(≖‿≖ԅ)'
      render :new
    end
  end

  def new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/stashes_controller.rb
class StashesController < ApplicationController
  def index
    @stashes = Stash.all
  end

  def new
  end

  def create
    user = User.find(params[:user_id])
    game = Game.find(params[:game_id]) # Need to clarify what params will be called
    if !user.games.find_by(id: game.id)
      user.games << game
    else
      flash[:alert] = "Game already exists in your collection"
    end
    redirect_to :back
  end

  def destroy
    Stash.find(params[:id]).destroy
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    user = User.new(user_params)

    if user.save
      flash[:welcome] = "(╯✧∇✧)╯ Welcome!"
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "User was not created. Try again."
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(user_params)
      redirect_to user_path(user)
    else
      flash[:error] = user.errors.full_messages.to_sentence
    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def destroy
    User.find(session[:user_id]).destroy
    reset_session
    flash[:success] = "User terminated"
    redirect_to '/users/new'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  include VotingHelper

  def upvote
    @game = Game.find_by(id: params[:id])
    @vote = current_user.votes.new(game: @game, value: 1)
    respond_to_voting
  end

  def downvote
    @game = Game.find_by(id: params[:id])
    @vote = current_user.votes.new(game: @game, value: -1)
    respond_to_voting
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_user_helper.rb
module CurrentUserHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def has_game?(game)
    current_user.games.include?(game) ? true : false
  end

  def user_stash(game)
    Stash.where(user: current_user, game: game).first
  end

  def is_friend
    user = User.find(params[:id])
    current_user
    return current_user.friends.include?(user)
  end

  def this
    current_user == User.find(params[:id])
  end

end

app/helpers/voting_helper.rb
module VotingHelper
  def respond_to_voting
    if @vote.save
      @new_score = @game.vote_score
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js {render nothing: true}
      end
    end
  end
end

app/views/categories/_category_card.html.erb
<div class="category-card" id="category-<%= category.id %>">
  <h4 class="center-header"><%= link_to category.name, category_path(category) %></h4>
  <div class="category-image">
    <img src="http:<%=category.games.sample.thumbnail_url %>">
  </div>
  <p class="center-header">Games: <span class="games-count"><%= category.games.count %></span></p>
</div>

app/views/categories/index.html.erb
<h2 class="center-header">All Categories</h2>

<div class="sort-panel">
  <span>Sort by: </span>
  <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default">A-Z</button>
    <button type="button" class="btn btn-default">Z-A</button>
    <button type="button" class="btn btn-default">Most Games</button>
    <button type="button" class="btn btn-default">Fewest Games</button>
  </div>
</div>

<div id="category-container">
  <% @categories.each do |cat| %>
    <%= render partial: 'categories/category_card', locals: {category: cat} %>
  <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<h2 class="center-header">All games in: <strong><%= @category.name %></strong>.</h2>

<%= render partial: 'games/sort_panel' %>

<div id="game-container">
  <% @category.games.each do |game| %>
    <%= render partial: 'games/game_card', locals: {game: game} %>
  <% end %>
</div>

app/views/comments/_destroy.html.erb
<%= form_for :comment, method: :delete, url: game_comment_path(@game, comment.id), confirm: "Are you sure?" do |f| %>
  <input type='hidden' name='game_id' value="<%= @game.id %>">

  <%= f.button "Delete", class: "btn btn-primary" %>
<% end %>

app/views/comments/_index.html.erb
<h4>Comments for <%= game.name %>:</h4>
<ul>
  <% @game.comments.each do |comment| %>
    <li>
      <p><%= comment.content %></p>
      <p>by: <%= comment.commenter.name %></p>
    </li>

    <% if current_user %>
      <%= render partial: 'comments/destroy', locals: {comment: comment} %>
    <% end %>
  <% end %>
</ul>

app/views/comments/_new.html.erb
<%= form_for :comment, url: game_comments_path(@game, @comment), class:"form-group" do |f|  %>
  <p>
    <%= f.label "Add a comment" %><br>
    <%= f.text_area :content, class:"form-control", rows:"3" %>
  </p>
  <p>
    <%= f.submit :Comment, class:"btn btn-primary" %>
  </p>
<% end %>

app/views/games/_game_card.html.erb
<div class="game-card" id="game-<%= game.id %>">
  <h4><%= link_to game.name, game_path(game) %></h4>
  <div class="game-image">
    <img src="http:<%=game.thumbnail_url %>">
  </div>
  <div class="votes">
    <%= link_to raw('<span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span>'), upvote_game_path(game), method: "post", remote: true %>
    <span class="vote-score"><%= game.vote_score %></span>
    <%= link_to raw('<span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>'), downvote_game_path(game), method: "post", remote: true %>
  </div>
  <p class="comment-count">Comments: <%= game.comments.count %></p>
  <div class="image-action">
    <% if current_user %>
      <% if has_game?(game) %>
        <%= render partial: "stashes/destroy", locals: {game: game} %>
      <% else %>
        <%= render partial: "stashes/new", locals: {game: game} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/_sort_panel.html.erb
<div class="sort-panel">
  <span>Sort by: </span>
  <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default">A-Z</button>
    <button type="button" class="btn btn-default">Z-A</button>
    <button type="button" class="btn btn-default">Highest Rated</button>
    <button type="button" class="btn btn-default">Most Commented</button>
  </div>
</div>

app/views/games/index.html.erb
<h1 class="center-header">All Games!</h1>

<%= render partial: 'games/sort_panel' %>

<div id="game-container">
  <% @games.each do |game| %>
    <%= render partial: 'games/game_card', locals: {game: game} %>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="game-details">
  <h3><%= @game.name %></h3>
    <img class="game-image" src="<%= @game.thumbnail_url %>">
    <h5><%= @game.min_players %> - <%= @game.max_players %> players</h5>
    <h5>~<%= @game.playing_time %> minutes</h5>
  <p><%= @game.description.gsub(/(&#10;)/, "").gsub(/(&quot;)/, "").gsub(/(&egrave;te)/, "").gsub(/(&#195;)/, "").gsub(/(&#170;te)/, "") %></p>
  <% if @game.year_published || @game.min_age %>
    <p><strong>Year published:</strong> <%= @game.year_published %></p>
    <p><strong>Ages:</strong> <%= @game.min_age %> and up</p>
  <% end %>
  <h3>Categories</h3>
  <ul>
    <% @game.categories.each do |cat| %>
      <li><%= link_to cat.name, category_path(cat)%></li>
    <% end %>
  </ul>
</div>
<section class="comments">
  <% if current_user %>
    <%= render partial: 'comments/new', locals: {game: @game} %>
  <% end %>
  <%= render partial: 'comments/index', locals: {game: @game, comments: @game.comments} %>
</section>

app/views/stashes/_destroy.html.erb
<%= form_for :stash, method: :delete, url: user_stash_path(current_user, user_stash(game)) do |f|%>
  <input type="hidden" name="game_id" value="<%= game.id %>">
  <%= f.button "Remove", class: "btn btn-danger" %>
<% end %>

app/views/stashes/_new.html.erb
<%= form_for :thisdoesntmatter, url: user_stashes_path(current_user), id: game.id do |f|%>
  <input type="hidden" name="game_id" value="<%= game.id %>">
  <%= f.button "Add", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% if flash[:error] %>
  <marquee behavior="slide" direction="right"><%= flash[:error] %></marquee>
<% end %>
<div class="container">
  <h1>Edit your profile</h1>
  <%= form_for @user, method: "patch", url: @user do |f|  %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.submit :Update, class: "btn btn-primary" %>
    </p>
  <% end %>

  <h6><%= button_to 'Delete', @user, method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %></h6>
</div>

app/views/users/index.html.erb
<div class="container">
  <h3>Board Game Enthusiasts</h3>
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to(user.name, user_path(user)) %></li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<% if flash[:success] %>
  <marquee behavior="slide" direction="right"><%= flash[:success] %></marquee>
<% elsif flash[:error] %>
  <marquee behavior="slide" direction="right"><%= flash[:error] %></marquee>
<% end %>
<div class="container">
  <h1>Register</h1>
    <%= form_for :user, url: users_path, class:"form-group" do |f|  %>
      <p>
        <%= f.label :name, class:"form-group" %>
        <%= f.text_field :name, class:"form-group" %>
      </p>
      <p>
        <%= f.label :email %>
        <%= f.email_field :email, class:"form-group" %>
      </p>
      <p>
        <%= f.label :password %>
        <%= f.password_field :password, class:"form-group" %>
      </p>
      <p>
        <%= f.submit :Register, class:"btn btn-primary" %>
      </p>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <% if flash[:welcome] %>
    <marquee behavior="slide" direction="right"><%= flash[:welcome] %></marquee>
  <% end %>
  <h2><%= @user.name %>'s profile!</h2>

  <% if this %>
    <%= link_to "Edit Profile", [:edit, @user] %>
  <% end %>

  <% if this || is_friend %>
    <h3 class="center-header">Friends:</h3>
    <ul>
      <% @user.friends.each do |friend| %>
        <% friendship = Friendship.where(user: @user, friend: friend).first %>
        <li><%= link_to("#{friend.name}", user_path(friend)) %>
          <span><%= button_to "Unfriend", user_friendship_path(@user, friendship), {method: :delete, class: "btn btn-danger"}  %> </span>
        </li>
      <% end %>
    </ul>
    <hr>
    <h3 class="center-header">Games:</h3>
    <%= render partial: 'games/sort_panel' %>
    <div id="game-container">
      <% @user.games.each do |game| %>
        <%= render partial: 'games/game_card', locals: {game: game} %>
      <% end %>
    </div>
    <% else %>
      <%= render partial: 'friendships/add_friend', locals: { user: @user} %>
  <% end %>
</div>

app/views/votes/downvote.js.erb
var $gameCard = $("#game-container").find("#game-" + <%= @game.id %>)
$gameCard.find('.vote-score').text("<%= @new_score %>")

app/views/votes/upvote.js.erb
var $gameCard = $("#game-container").find("#game-" + <%= @game.id %>)
$gameCard.find('.vote-score').text("<%= @new_score %>")